PreCommit:
  AuthorName:
    enabled: false
  RuboCop:
    enabled: false
    command: ['bundle', 'exec', 'rubocop']
  EsLint:
    enabled: true
    command: ['./node_modules/.bin/eslint', './app/frontend/*', '-c', '.eslintrc']
    include: '**/*.jsx'
