AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - db/schema.rb
    - tmp/**/*
Rails:
  Enabled: true
# permit -> of lambda
Lambda:
  Enabled: false
# permit Module::Class definition
ClassAndModuleChildren:
  Enabled: false
LineLength:
  Max: 100
Style/FrozenStringLiteralComment:
  Enabled: false
