AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - db/schema.rb
    - tmp/**/*
Rails:
  Enabled: true
# permit -> of lambda
Lambda:
  Enabled: false
# permit Module::Class definition
ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
