development:
  adapter: async

test:
  adapter: async

staging:
  adapter: sidekiq
  url: redis://
  channel_prefix: andres_cms_staging

production:
  adapter: sidekiq
  url: redis://
  channel_prefix: andres_cms_production
