development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: redis://rediscloud:wYLFiSgQ27rdgke7PXVRSxraxSDX7BFL@redis-14632.c12.us-east-1-4.ec2.cloud.redislabs.com:14632
  channel_prefix: andres_cms_staging

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: andres_cms_production
